### ISSUE TITLE
Some questions regarding VideoPublisher

### ISSUE THREAD

**Issue by rubytastic** [MonaSolutions/MonaClients#1]
Some questions regarding your VideoPublisher example

Is it possible to:
- limit record time to X seconds?
- trigger event on server after record to convert it with ffmpeg to a movie file 
- set a filename and connect to a database or return filename to REST interface for communication to external database?

Please contact me on github directly on these questions. 
Payed support regarding these above items is no problem if possible to implement or provide example.
Thank you.

**Comment by thomasjammet** [comment]
Hi rubytastic,

Yes all these things are possible in lua script, can you contact me on gmail to discuss furthermore on your needs.

I can develop or help you to develop if you prefer.
