### ISSUE TITLE
Low quality on video publisher

### ISSUE THREAD

**Issue by rubytastic** [MonaSolutions/MonaClients#2]
The quality on video publisher is low, 
Any thoughts on how to make it a higher quality? 

H264 encoding should allow full HD recordings?
Ive digged the docs but flex is not my native language; any suggestions in this regard?

**Comment by thomasjammet** [comment]
Hi Rubytastic,

There is no limit of quality in your publications. You are only limited to
the supported formats of your camera. You can try the latest version of the
client VideoPublisher
http://raspi.monaserver.ovh/MonaClients/VideoPublisher/ which allows you
to change the quality of the publication. Then you could adapt the source
code to your needs.

I hope it will help you

_--_

_Thomas JAMMET_

2015-05-12 18:13 GMT+02:00 rubytastic notifications@github.com:

**Comment by thomasjammet** [comment]
Sorry I've forgotten a really important parameter : the bitrate. The format
change only the size of the stream.
So you have to use the function _setQuality *
http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/media/Camera.html#setQuality%28%29of
your *Camera_. The parameters bandwith and quality affect directly the
encoding quality of your publication.

(I have to update VideoPublisher with an input for these parameters)

_--_

_Thomas JAMMET_
Freelancer - MonaServer.ovh
2 Rue Mila - 82000 Montauban (France)
Tel : _+336 23 46 39 80_
http://fr.linkedin.com/pub/thomas-jammet/5a/411/60b/

2015-05-12 18:29 GMT+02:00 Thomas Jammet jammetthomas@gmail.com:

**Comment by rubytastic** [comment]
Thank you Thomas, much appreciated.
The setQuality param does the trick. 0,100 for max quality
