### ISSUE TITLE
Question about mic sources in VideoPublisher

### ISSUE THREAD

**Issue by und3f1ned** [MonaSolutions/MonaClients#3]
Question regarding VideoPublisher. For example: I have 2 microphones. How can I choose another source for microphone? Thank you!

**Comment by thomasjammet** [comment]
Hi,

I have update VideoPublisher to support multiple microphones, how is it working for you?
Also which browser are you using? I have seen that now chrome require HTTPS to allow device access to Flash and Firefox 55 seems not working good with Flash publishers.

**Comment by und3f1ned** [comment]
Wow, that's great. Working perfectly with chrome. Thank you very much!
